version: 2
jobs:
  unit-test-beta:
    docker:
      - image: cimg/rust

    working_directory: ~/repo

    steps:
      - checkout
      - run: cargo build --release
workflows:
  version: 2
  build-test-deploy-beta:
    jobs:
      - unit-test-beta:
          filters:
            branches:
              only: main
